// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp3v7MSl1sedG5xwA2FgiqynjMXtX4e98',
    appId: '1:679456737875:web:8f5a060a1b7ee00eb194a6',
    messagingSenderId: '679456737875',
    projectId: 'my-app-f3d46',
    authDomain: 'my-app-f3d46.firebaseapp.com',
    databaseURL: 'https://my-app-f3d46-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-f3d46.appspot.com',
    measurementId: 'G-TMT1PNPKZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwekkG0An1DIS8JijTU3U5TUw9ueXSlBU',
    appId: '1:679456737875:android:60ea092f3e55f25bb194a6',
    messagingSenderId: '679456737875',
    projectId: 'my-app-f3d46',
    databaseURL: 'https://my-app-f3d46-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-f3d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pM8JwKi9E4kx4g3ZHiTG0XBqkctF_ZA',
    appId: '1:679456737875:ios:6afbd5ba2aa54107b194a6',
    messagingSenderId: '679456737875',
    projectId: 'my-app-f3d46',
    databaseURL: 'https://my-app-f3d46-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-f3d46.appspot.com',
    androidClientId: '679456737875-l3fa72a5blrqaiuge1s6h4cra1a9rl3g.apps.googleusercontent.com',
    iosClientId: '679456737875-sfpfjtadv4uq7dla8le7qi6s9ujouob5.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8pM8JwKi9E4kx4g3ZHiTG0XBqkctF_ZA',
    appId: '1:679456737875:ios:8b3a00b18847b275b194a6',
    messagingSenderId: '679456737875',
    projectId: 'my-app-f3d46',
    databaseURL: 'https://my-app-f3d46-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-f3d46.appspot.com',
    androidClientId: '679456737875-l3fa72a5blrqaiuge1s6h4cra1a9rl3g.apps.googleusercontent.com',
    iosClientId: '679456737875-mbavjbi5gk0sn2c3dvv3kqv7m8468r9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectApp.RunnerTests',
  );
}
